// Code generated by "stringer -type StorageNotifyEventType storage_notify_event_type.go"; DO NOT EDIT.

package pubsub

import "fmt"

const _StorageNotifyEventType_name = "ObjectFinalizeObjectMetaDataUpdateObjectDeleteObjectArchive"

var _StorageNotifyEventType_index = [...]uint8{0, 14, 34, 46, 59}

func (i StorageNotifyEventType) String() string {
	if i < 0 || i >= StorageNotifyEventType(len(_StorageNotifyEventType_index)-1) {
		return fmt.Sprintf("StorageNotifyEventType(%d)", i)
	}
	return _StorageNotifyEventType_name[_StorageNotifyEventType_index[i]:_StorageNotifyEventType_index[i+1]]
}
